export const SET_SELECTED_MONTH = "SET_SELECTED_MONTH";

export const LOGOUT = "LOGOUT";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

export const ADD_TASK_REQUEST = "ADD_TASK_REQUEST";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const ADD_TASK_ERROR = "ADD_TASK_ERROR";

export const GET_TASKS_OF_DAY_REQUEST = "GET_TASKS_OF_DAY_REQUEST";
export const GET_TASKS_OF_DAY_SUCCESS = "GET_TASKS_OF_DAY_SUCCESS";
export const GET_TASKS_OF_DAY_ERROR = "GET_TASKS_OF_DAY_ERROR";
